### PR TITLE
Fixes Issue #176 which caused torch.compile to graphbreak and fail with float8

### PR DESCRIPTION
**Pull request by drisspg**
# Summary

Attempts to fix https://github.com/pytorch-labs/float8_experimental/issues/176

Current test_compile errors:
```Shell
                        (output, treespec),
                        graph,
                        lifted_freevars,
                    )
    
        except Unsupported as ex:
            f_name = f"{type(f).__name__}"
            if isinstance(f, UserFunctionVariable):
                f_name = f.get_name()
            msg = (
                f"speculate_subgraph: while introspecting {description}, we were unable "
                f"to trace function `{f_name}` into a single graph. This means "
                f"that Dynamo was unable to prove safety for this API and will "
                f"fall back to eager-mode PyTorch, which could lead to a slowdown."
            )
            log.warning(msg)
            log.exception(ex)
>           raise Unsupported(
                f"{msg} Scroll up for the stack trace "
                f"of the initial exception. The reason was: {ex.msg}"
            ) from ex
E           torch._dynamo.exc.Unsupported: speculate_subgraph: while introspecting autograd.Function, we were unable to trace function `backward` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown. Scroll up for the stack trace of the initial exception. The reason was: call_function UserDefinedClassVariable() [TensorVariable(), TensorVariable(), ConstantVariable(dtype)] {'emulate': ConstantVariable(bool)}
E           
E           from user code:
E              File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 62, in forward
E               y = self.cast_to_float8e5m2_bw(y)
E             File "/home/drisspg/meta/float8_experimental/float8_experimental/dynamic_linear/dynamic_float8_linear.py", line 79, in cast_to_float8e5m2_bw
E               return NoopFwToFloat8E5M2Bw.apply(gradY, self.emulate)
E           
E           Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
E           
E           
E           You can suppress this exception and fall back to eager by setting:
E               import torch._dynamo
E               torch._dynamo.config.suppress_errors = True

../../miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py:328: Unsupported
---------------------------------------- Captured stderr call -----------------------------------------
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [WARNING] speculate_subgraph: while introspecting autograd.Function, we were unable to trace function `backward` into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown.
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR] call_function UserDefinedClassVariable() [TensorVariable(), TensorVariable(), ConstantVariable(dtype)] {'emulate': ConstantVariable(bool)}
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR] Traceback (most recent call last):
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 256, in speculate_subgraph
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     output = f.call_function(tx, args, sub_kwargs)
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 255, in call_function
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return super().call_function(tx, args, kwargs)
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 84, in call_function
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return tx.inline_user_function_return(
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 650, in inline_user_function_return
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2245, in inline_call
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]     return cls.inline_call_(parent, func, args, kwargs)
[2024-01-02 15:43:30,115] [29/0] torch._dynamo.variables.higher_order_ops: [ERROR]   File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2354, in inline_call_

```

### CODE REVIEW

**Comment by vkuzo** [comment]
nice! does test/test_everything.sh pass?

**Review by vkuzo — APPROVED** [review]

**Comment by drisspg** [comment]
Yup, should have added that note, ran `./test/test_everything.sh` and all tests are green.
Except for 
``` Shell
-------------------------------------------Mode: analyze--------------------------------------------
output testing single_gpu vs FSDP success
Traceback (most recent call last):
  File "/home/drisspg/meta/float8_experimental/test/test_fsdp.py", line 263, in <module>
    fire.Fire(run)
  File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/drisspg/miniconda3/envs/nightly/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/drisspg/meta/float8_experimental/test/test_fsdp.py", line 219, in run
    v2 = sd_out_fsdp[k]
KeyError: '0.weight'
```

**Comment by vkuzo** [comment]
maybe confirm if this PR breaks it?  the tests all pass on my end with the old nightly.

**Comment by drisspg** [comment]
Yup, should have added that note, ran `./test/test_everything.sh` and all tests are green. Except for test_sam which appears to be broken on main for a sqnr assert failure

**Pull request closed without merging**
