### PR TITLE
[wip] enable Float8Tensor as subgraph boundary

### PR DESCRIPTION
**Pull request by vkuzo**
Summary:

Explorations to see how we can enable graph breaks with Float8Tensor at the boundary.

This may be blocking composability of Float8Linear + FSDP + torch.compile.

Test Plan:

```
pytest test/test_compile.py -s --sw -k graph_break
// currently broken
// logs: https://gist.github.com/vkuzo/53e92dfd91879c0710975b8a657fd91d

pytest test/test_compile.py -s --sw -k test_float8_graph_input 2>&1 | with-proxy gh gist create
// works!
// logs: https://gist.github.com/vkuzo/7a4c7252010157aa49f48a24046ec014

pytest test/test_compile.py -s --sw -k test_float8_graph_output 2>&1 | with-proxy gh gist create
// broken, has fake tensors when it should have real tensors
// logs: https://gist.github.com/vkuzo/35230bb05902733a58c19a7e1f04da45
```

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by drisspg** [comment]
Since I think that this might be hard to solve, should we make an issue tracking this and `xfail` the test?

**Comment by bdhirsh** [comment]
It might be worth treating these two tests separately:

(1) a test with a graph break in the middle

(2) a test with no graph breaks, but where we manually pass a `Float8Tensor` as a user input (or return one as a user output)

That way we can tell if the problem is specific to "Float8Tensor as graph input", or if it some more subtle bug around graph breaks

**Comment by vkuzo** [comment]
opened https://github.com/pytorch/pytorch/issues/117115 to track this in PyTorch repo

**Comment by vkuzo** [comment]
> It might be worth treating these two tests separately:
> 
> (1) a test with a graph break in the middle
> 
> (2) a test with no graph breaks, but where we manually pass a `Float8Tensor` as a user input (or return one as a user output)
> 
> That way we can tell if the problem is specific to "Float8Tensor as graph input", or if it some more subtle bug around graph breaks

@bdhirsh , good idea, I added testing for input and output and added the results to the summary  The "float8tensor as output" case is fishy, we see fake tensors.

**Pull request closed without merging**
